FROM ubuntu:22.04
# ARG VERSION
RUN apt-get update && apt-get install -y \
    openssh-server
RUN mkdir /var/run/sshd
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
RUN ssh-keygen -A
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
