[redis_masters]
master1 ansible_host=10.10.0.11 ansible_user=root ansible_password=root123
master2 ansible_host=10.10.0.12 ansible_user=root ansible_password=root123
master3 ansible_host=10.10.0.13 ansible_user=root ansible_password=root123


[redis_replicas]
replica1 ansible_host=10.10.0.14 ansible_user=root ansible_password=root123
replica2 ansible_host=10.10.0.15 ansible_user=root ansible_password=root123
replica3 ansible_host=10.10.0.16 ansible_user=root ansible_password=root123


[redis_nodes:children]
redis_masters
redis_replicas

